### ISSUE TITLE
JSON: raise user-arguments to top-level

### ISSUE THREAD

**Issue by ericphanson** [JuliaLogging/LoggingFormats.jl#12]
from the README, we have
```julia
julia> using LoggingFormats, LoggingExtras

julia> with_logger(FormatLogger(LoggingFormats.JSON(; recursive=true), stderr)) do
                  @info "hello, world" key=Dict("hello" => true)
       end
{"level":"info","msg":"hello, world","module":"Main","file":"REPL[18]","line":2,"group":"REPL[18]","id":"Main_ffce16b5","kwargs":{"key":{"hello":true}}}
```
But I think it would be nicer as
```
{"level":"info","msg":"hello, world","module":"Main","file":"REPL[18]","line":2,"group":"REPL[18]","id":"Main_ffce16b5", "key":{"hello":true}}
```
i.e. without the extra nesting with `kwargs`

**Comment by fredrikekre** [comment]
Makes sense. Would just have to handle the case where the key conflicts with a standard key then (like `msg` etc).

**Comment by ericphanson** [comment]
I think it would also have to be opt-in or a breaking release, since I know I at least rely on the current structure in downstream log queries and stuff like that, and the current semantics are documented (in that readme example at least).

**Comment by fredrikekre** [comment]
Sure, could be a kwarg to the `JSON` constructor (good example of why it is better to use an instance and not just the type).
